version: '3'

services:
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: toor
            MYSQL_DATABASE: MyDb
            MYSQL_USER: myuser
            MYSQL_PASSWORD: myuserpassword
        ports:
            - 3306:3306